// Server-renders /blog and /post/<slug>. All logic lives in the typed
// ../lib/blog-page-handler.ts. The two ../ssr imports are generated by
// `npm run build` (vite build --ssr), so this file is excluded from `tsc`
// (tsconfig.node.json): they don't exist when type-checking runs. It must stay
// TypeScript: Netlify bundles .mts functions with esbuild, but ships .mjs
// files unbundled, which can't resolve the app's dependencies at runtime.
import type { Config, Context } from '@netlify/functions';
import { renderApp } from '../ssr/render-app.js';
import template from '../ssr/index-template.js';
import { createBlogPageHandler } from '../lib/blog-page-handler.ts';
import { fromNetlifyContext } from '../lib/handler-context.ts';

export default async (request: Request, context: Context) =>
  createBlogPageHandler({ renderApp, template })(request, fromNetlifyContext(context));

export const config: Config = { path: ['/blog', '/post/:slug'] };
